name: Script cron

on:
    schedule:
        - cron: "0 5 * * *"

    workflow_dispatch:

env:
    GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Run the script
              run: bash script.sh

            - name: Upload files
              uses: actions/upload-artifact@v2
              with:
                  path: databases

            - name: Update release
              run: gh release upload latest databases/* --clobber
